# Generated by Django 4.1.2 on 2022-12-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_paymentmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='card_name',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
