# Generated by Django 4.1.2 on 2022-12-09 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_booking_room_no_paymentmaster_card_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(default=0)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('rprice', models.IntegerField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.category')),
                ('gname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.guest')),
                ('rno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.rooms')),
            ],
            options={
                'db_table': 'Bookingss',
            },
        ),
    ]
